import enum

class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    INVESTIGATOR = "INVESTIGATOR"
    ANALYST = "ANALYST"

class UserStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class ClaimStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FLAGGED_FRAUD = "FLAGGED_FRAUD"
    CLOSED = "CLOSED"

class ClaimType(str, enum.Enum):
    INPATIENT = "INPATIENT"
    OUTPATIENT = "OUTPATIENT"
    EMERGENCY = "EMERGENCY"
    PHARMACY = "PHARMACY"
    DAYCARE = "DAYCARE"

class RiskLevel(str, enum.Enum):
    NORMAL = "NORMAL"      # Score 0-19
    LOW = "LOW"            # Score 20-39
    MEDIUM = "MEDIUM"      # Score 40-59
    HIGH = "HIGH"          # Score 60-79
    CRITICAL = "CRITICAL"  # Score 80-100

class FraudCategory(str, enum.Enum):
    NONE = "NONE"
    BILLING_FRAUD = "BILLING_FRAUD"
    PROVIDER_FRAUD = "PROVIDER_FRAUD"
    MEMBER_FRAUD = "MEMBER_FRAUD"
    IDENTITY_FRAUD = "IDENTITY_FRAUD"
    PRESCRIPTION_FRAUD = "PRESCRIPTION_FRAUD"
    DUPLICATE_CLAIMS = "DUPLICATE_CLAIMS"
    UPCODING = "UPCODING"
    PHANTOM_SERVICES = "PHANTOM_SERVICES"
    UNNECESSARY_HOSPITALIZATION = "UNNECESSARY_HOSPITALIZATION"

class InvestigationStatus(str, enum.Enum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    UNDER_REVIEW = "UNDER_REVIEW"
    INFORMATION_REQUIRED = "INFORMATION_REQUIRED"
    ESCALATED = "ESCALATED"
    CONFIRMED_FRAUD = "CONFIRMED_FRAUD"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    CLOSED = "CLOSED"

class RuleSeverity(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class ReportStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ReportType(str, enum.Enum):
    FRAUD_SUMMARY = "FRAUD_SUMMARY"
    PROVIDER_FRAUD = "PROVIDER_FRAUD"
    MEMBER_FRAUD = "MEMBER_FRAUD"
    INVESTIGATOR_PERFORMANCE = "INVESTIGATOR_PERFORMANCE"
    FRAUD_TREND = "FRAUD_TREND"
    INVESTIGATION_REPORT = "INVESTIGATION_REPORT"
